import { MySQL, SQLDialect } from '@codemirror/lang-sql';

const custom_keywords: string[] = [
    'hive_check_column',
    'drop',
    'table_identifier',
    'external',
    'partitioned',
    'clustered',
    'sorted',
    'into',
    'buckets',
    'row_format',
    'num_buckets',
    'stored',
    'location',
    'tblproperties',
    'select_statement',
    'parquet',
    'sort',
    'length',
    'concat',
    'concat_ws',
    'ascii',
    'Instr',
    'levenshtein',
    'locate',
    'regexp_extract',
    'soundex',
    'substr',
    'substring',
    'starts_with',
    'ends_with',
    'backup_partitioned_auto',
    'backup_schema',
    'is_empty',
    'non_empty',
    'find_first_in',
    'find_all_in',
    'position',
    'move_table_to_schema',
    'rollback_partitioned_auto',
    'overwrite',
    'base64',
    'decode',
    'encode',
    'md5',
    'format_number',
    'decode_any',
    'format_string',
    'initcap',
    'lpad',
    'ltrim',
    'regexp_replace',
    'unbase64',
    'rpad',
    'rtrim',
    'replace_all_in',
    'replace_first_in',
    'split',
    'substring_index',
    'overlay',
    'translate',
    'trim',
    'reverse',
    'lcase',
    'lower',
    'to_lower_case',
    'ucase',
    'upper',
    'to_upper_case',
    'hex',
    'sentences',
    '$',
    'TRY',
    'try',
    'CATCH',
    'catch',
    'spark',
    'hive',
    'close_engine',
    'get_table_hdfs_loc',
    'get_table_name_and_schema',
    'get_hive_table_count_row',
    'get_partition_columns_list',
    'get_partition_list',
    'let',
    'hive_check_partition_exists',
    'hive_check_schema',
    'hive_check_table',
    'hive_check_table_data_exists',
    'hive_drop_partitions',
    'hive_drop_partitions_except_last_ones',
    'hive_drop_partitions_except_one_if_it_exists',
    'hive_drop_table',
    'hive_drop_table_partitions',
    'hive_drop_table_partitions_by_condition',
    'hive_is_table_partitioned',
    'hive_table_exists',
    'hive_truncate_tables',
    'check_hdfs_path_is_dir',
    'check_hdfs_path_is_file',
    'copy_file_from_hdfs_to_local',
    'create_hdfs_dir',
    'delete_hdfs_dir',
    'exists_hdfs_dir',
    'get_list_of_hdfs_files',
    'read_hdfs_file',
    'rename_hdfs_dir',
    'write_to_file',
    'log_info',
    'log_error',
    'log_debug',
    'log_warn',
    'get_stats',
    'publish',
    'set_ctl_loading_status',
    'log_kibana',
    'Unit',
    'run_sql',
    'run_sql_hdfs',
    'run_sql_base64',
    'run_sql_ansi',
    'sh',
    'cdc_calc',
    'coalesce_files',
    'MSCK',
    'msck',
];

const custom_types: string[] = ['byte', 'short', 'long', 'struct', 'string'];

export const createB2CDialect = (userParams?: string[]) => {
    if (!userParams) {
        return B2CDialect;
    }

    return SQLDialect.define({
        ...MySQL.spec,
        keywords:
            MySQL.spec.keywords +
            ' ' +
            userParams.join(' ') +
            ' ' +
            custom_keywords.join(' '),
        types: MySQL.spec.types + ' ' + ' ' + custom_types.join(' '),
    });
};

export const B2CDialect: SQLDialect = SQLDialect.define({
    ...MySQL.spec,
    keywords: MySQL.spec.keywords + ' ' + custom_keywords.join(' '),
    types: MySQL.spec.types + ' ' + custom_types.join(' '),
});

export const convertStringToBoolean = (value: string) =>
    JSON.parse(value.toLocaleLowerCase());

export const convertBooleanToString = (value: boolean) => String(value);
